<a href="https://colab.research.google.com/github/mohamedssafini/pyTorch/blob/master/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class MyNeuralNet(nn.Module):
    def __init__(self, input_size, n_nodes, output_size):
        super(MyNeuralNet, self).__init__()
        self.operationOne = nn.Linear(input_size, n_nodes)
        self.operationTwo = nn.Linear(n_nodes, output_size)
    def forward(self, x):
        x = F.relu(self.operationOne(x))
        x = self.operationTwo(x)
        x = F.sigmoid(x)
        return x

In [0]:
my_network = MyNeuralNet(input_size = 3, n_nodes = 2, output_size = 1)

In [5]:
import torch
first_order_tensor = torch.tensor([1, 2, 3])
print(first_order_tensor)

tensor([1, 2, 3])


In [6]:
print(first_order_tensor[0])

tensor(1)


In [7]:
print(first_order_tensor[0:2])

tensor([1, 2])


In [8]:
print(first_order_tensor[1:])

tensor([2, 3])


In [11]:
second_order_tensor = torch.tensor([ [ 11, 12, 13 ],
 [ 21, 22, 23 ]
 ])
print(second_order_tensor)

tensor([[11, 12, 13],
        [21, 22, 23]])


In [12]:
print(second_order_tensor[0, 1])

tensor(12)


In [0]:
fourth_order_tensor = torch.tensor(
[
 [
 [
 [1111, 1112],
 [1121, 1122]
 ],
 [
 [1211, 1212],
 [1221, 1222]
 ]
 ],
 [
 [
 [2111, 2112],
 [2121, 2122]
 ],
 [
 [2211, 2212],
 [2221, 2222]
 ]
 ]
])


In [20]:
print(fourth_order_tensor)

tensor([[[[1111, 1112],
          [1121, 1122]],

         [[1211, 1212],
          [1221, 1222]]],


        [[[2111, 2112],
          [2121, 2122]],

         [[2211, 2212],
          [2221, 2222]]]])


In [18]:
print(fourth_order_tensor[1,0,1,1])

tensor(2122)


In [19]:
my_tensor = torch.tensor([1, 2, 3, 4, 5])
print(my_tensor.size())

torch.Size([5])


In [21]:
print(fourth_order_tensor.size())

torch.Size([2, 2, 2, 2])


In [22]:
random_tensor = torch.rand([4, 2])
print(random_tensor)

tensor([[0.9708, 0.1590],
        [0.2331, 0.4121],
        [0.8751, 0.0032],
        [0.8992, 0.8301]])


In [23]:
random_tensor.view([2, 4])

tensor([[0.9708, 0.1590, 0.2331, 0.4121],
        [0.8751, 0.0032, 0.8992, 0.8301]])

In [0]:
random_tensor = torch.rand([4, 2, 4])

In [26]:
print(random_tensor)

tensor([[[0.8808, 0.4432, 0.3066, 0.2252],
         [0.1348, 0.3904, 0.7845, 0.2285]],

        [[0.2007, 0.7031, 0.6942, 0.7205],
         [0.5339, 0.7711, 0.2259, 0.5736]],

        [[0.0585, 0.7303, 0.6465, 0.6703],
         [0.7822, 0.6274, 0.1264, 0.5894]],

        [[0.9979, 0.8437, 0.5010, 0.7928],
         [0.2475, 0.6575, 0.8692, 0.1799]]])


In [27]:
random_tensor.view([2, 4, -1])

tensor([[[0.8808, 0.4432, 0.3066, 0.2252],
         [0.1348, 0.3904, 0.7845, 0.2285],
         [0.2007, 0.7031, 0.6942, 0.7205],
         [0.5339, 0.7711, 0.2259, 0.5736]],

        [[0.0585, 0.7303, 0.6465, 0.6703],
         [0.7822, 0.6274, 0.1264, 0.5894],
         [0.9979, 0.8437, 0.5010, 0.7928],
         [0.2475, 0.6575, 0.8692, 0.1799]]])

In [28]:
random_tensor.view([2, -1, 4])

tensor([[[0.8808, 0.4432, 0.3066, 0.2252],
         [0.1348, 0.3904, 0.7845, 0.2285],
         [0.2007, 0.7031, 0.6942, 0.7205],
         [0.5339, 0.7711, 0.2259, 0.5736]],

        [[0.0585, 0.7303, 0.6465, 0.6703],
         [0.7822, 0.6274, 0.1264, 0.5894],
         [0.9979, 0.8437, 0.5010, 0.7928],
         [0.2475, 0.6575, 0.8692, 0.1799]]])

In [29]:
x = torch.tensor([5, 3])
y = torch.tensor([3, 2])
torch.add(x, y)

tensor([8, 5])

In [30]:
torch.sub(x, y)

tensor([2, 1])

In [31]:
torch.mul(x, y)

tensor([15,  6])

In [32]:
x + y

tensor([8, 5])

In [33]:
torch.div(x, y)

tensor([1, 1])

In [34]:
torch.matmul(x, y)

tensor(21)

In [35]:
x @ y

tensor(21)