<a href="https://colab.research.google.com/github/mohamedssafini/pyTorch/blob/master/Tensors_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [0]:
import torch

In [3]:
print(torch.__version__)

1.3.1


In [4]:
torch.cuda.is_available()

True

# Torch Tensors

In [5]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [7]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [8]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [9]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [10]:
print(b.shape[1])

3


In [0]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [0]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [0]:
print(c)
print(c.dtype)

tensor([[ 2.,  1.,  4.],
        [ 3.,  5.,  4.],
        [ 1.,  2.,  0.],
        [ 4.,  3.,  2.]])
torch.float32


In [0]:
print(d)
print(d.dtype)

tensor([[ 2.,  1.,  4.],
        [ 3.,  5.,  4.],
        [ 1.,  2.,  0.],
        [ 4.,  3.,  2.]], dtype=torch.float64)
torch.float64


In [0]:
print(c.mean())

tensor(2.5833)


In [0]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [0]:
print(c.std())

tensor(1.5050)


In [0]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [0]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[ 2],
        [ 1],
        [ 4],
        [ 3],
        [ 5],
        [ 4],
        [ 1],
        [ 2],
        [ 0],
        [ 4],
        [ 3],
        [ 2]])
tensor([ 2,  1,  4,  3,  5,  4,  1,  2,  0,  4,  3,  2])
tensor([[ 2,  1,  4,  3],
        [ 5,  4,  1,  2],
        [ 0,  4,  3,  2]])
tensor([[ 2,  1,  4,  3],
        [ 5,  4,  1,  2],
        [ 0,  4,  3,  2]])
tensor([[ 2,  1,  4,  3,  5,  4,  1,  2,  0,  4,  3,  2]])
torch.Size([1, 12])




tensor([[[ 0.2452, -0.2727, -1.2520, -2.5308],
         [-0.1989, -1.1197,  0.6911, -0.1573],
         [-0.1419, -0.1570,  0.1724, -0.8731]],

        [[ 0.3698,  1.7548, -0.0158, -1.9778],
         [ 1.7497,  0.0472,  0.7746,  0.6194],
         [ 0.0874,  1.0405,  0.0450, -0.6311]]])
tensor([[ 0.2452, -0.2727, -1.2520, -2.5308, -0.1989, -1.1197,  0.6911,
         -0.1573, -0.1419, -0.1570,  0.1724, -0.8731],
        [ 0.3698,  1.7548, -0.0158, -1.9778,  1.7497,  0.0472,  0.7746,
          0.6194,  0.0874,  1.0405,  0.0450, -0.

In [0]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[ 0.5186,  0.8387,  0.1570,  0.5122],
        [ 0.4223,  0.9927,  0.9147,  0.2779],
        [ 0.5273,  0.5849,  0.9200,  0.2523],
        [ 0.6333,  0.2193,  0.3354,  0.0160]])


In [0]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.8696,  0.1583, -0.0100, -0.3128],
        [-0.9579,  0.6632, -1.6259,  2.1361],
        [-0.6797, -0.2329,  0.4184, -0.1974],
        [ 0.1087,  0.7739,  0.0408,  0.3881]])
torch.float32


In [0]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([ 6.,  6.,  9.,  7.,  6.])
torch.float32


In [0]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[ 7.,  9.,  6.],
        [ 6.,  6.,  8.],
        [ 7.,  9.,  8.]])


In [0]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [0]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
torch.float32


In [0]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[-0.0438, -0.5338, -0.9729, -0.7514],
        [-0.5681,  1.3657,  1.7602,  0.0791],
        [ 0.1952,  1.0167,  0.4843,  0.0830],
        [-0.3008, -1.8261,  0.4665, -0.4238]], dtype=torch.float64)


In [0]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[-0.3510,  0.9970,  0.1470,  0.1994],
        [-0.5357,  1.6559, -0.7112,  2.4140],
        [-0.1524,  0.3520,  1.3384,  0.0549],
        [ 0.7420,  0.9932,  0.3761,  0.4040]])


In [0]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[-0.3510,  0.9970,  0.1470,  0.1994],
        [-0.5357,  1.6559, -0.7112,  2.4140],
        [-0.1524,  0.3520,  1.3384,  0.0549],
        [ 0.7420,  0.9932,  0.3761,  0.4040]])


In [0]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 0.9970,  1.6559,  0.3520,  0.9932])
tensor([[-0.3510,  0.9970],
        [-0.5357,  1.6559],
        [-0.1524,  0.3520],
        [ 0.7420,  0.9932]])
tensor([[-0.3510,  0.9970,  0.1470,  0.1994],
        [-0.5357,  1.6559, -0.7112,  2.4140],
        [-0.1524,  0.3520,  1.3384,  0.0549]])
tensor(1.00000e-02 *
       5.4926)
0.05492551624774933
tensor([-0.1524,  0.3520,  1.3384,  0.0549])


## Numpy Bridge

In [0]:
import numpy as np

In [0]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]
tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [0]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [0]:
#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[-0.3510,  0.9970,  0.1470,  0.1994],
        [-0.5357,  1.6559, -0.7112,  2.4140],
        [-0.1524,  0.3520,  1.3384,  0.0549],
        [ 0.7420,  0.9932,  0.3761,  0.4040]], device='cuda:0')


In [0]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[-0.3510,  0.9970,  0.1470,  0.1994],
        [-0.5357,  1.6559, -0.7112,  2.4140],
        [-0.1524,  0.3520,  1.3384,  0.0549],
        [ 0.7420,  0.9932,  0.3761,  0.4040]], device='cuda:0')


In [0]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([ 2,  3,  4,  1]) torch.int64


In [0]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]]) torch.float32


## Tensor Concatenation

In [0]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 0.6135,  0.8433, -1.1979, -0.6967,  1.0293],
        [ 0.7166,  1.0994,  1.4566,  0.7288,  0.8442]])
tensor([[ 1.3261,  0.4962,  0.8908, -0.0891,  0.2191],
        [ 0.4312,  0.8086, -0.7231,  0.5978,  0.1467],
        [-1.3080,  0.3101,  0.5747,  1.0255, -1.0372]])


tensor([[ 0.6135,  0.8433, -1.1979, -0.6967,  1.0293],
        [ 0.7166,  1.0994,  1.4566,  0.7288,  0.8442],
        [ 1.3261,  0.4962,  0.8908, -0.0891,  0.2191],
        [ 0.4312,  0.8086, -0.7231,  0.5978,  0.1467],
        [-1.3080,  0.3101,  0.5747,  1.0255, -1.0372]])


tensor([[ 0.1965, -0.7684,  0.2611],
        [-0.2699, -1.9723,  0.8114]])
tensor([[-0.2711,  0.0370, -2.2648,  0.1803,  0.9619],
        [-0.0567, -0.9806,  1.6391,  0.4946,  0.3042]])


tensor([[ 0.1965, -0.7684,  0.2611, -0.2711,  0.0370, -2.2648,  0.1803,
          0.9619],
        [-0.2699, -1.9723,  0.8114, -0.0567, -0.9806,  1.6391,  0.4946,
          0.3042]])




## Adding Dimensions to Tensors

In [0]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[ 1,  2,  3,  4]])
torch.Size([1, 4])
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4]])
torch.Size([4, 1])


tensor([[[ 0.9601,  0.0494,  0.8584,  0.4740],
         [ 0.4750,  0.1971,  0.2075,  0.4673],
         [ 0.2602,  0.0044,  0.4129,  0.3389]],

        [[ 0.6090,  0.3474,  0.7967,  0.0699],
         [ 0.2895,  0.6549,  0.3569,  0.9321],
         [ 0.7053,  0.3842,  0.0122,  0.9424]]])


tensor([[ 0.8584,  0.2075,  0.4129],
        [ 0.7967,  0.3569,  0.0122]])
torch.Size([2, 3])


tensor([[[ 0.8584],
         [ 0.2075],
         [ 0.4129]],

        [[ 0.7967],
         [ 0.3569],
         [ 0.0122]]])
torch.Size([2, 3, 1])


## AutoGrad

In [0]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([ 5.,  7.,  9.])
tensor(21.)


In [0]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([ 1.,  1.,  1.])


In [0]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [0]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 3.,  3.],
        [ 3.,  3.]])
tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)
tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [0]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])
tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])
